Get 7.8.2 builds working again

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,2 +1,28 @@
-language: haskell
-ghc: 7.8
+env:
+ - GHCVER=7.8.2
+
+before_install:
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-1.20 ghc-$GHCVER alex-3.1.3 happy-1.19.3
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.20/bin:/opt/alex/3.1.3/bin:/opt/happy/1.19.3/bin:$PATH
+
+install:
+ - cabal update
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks
+
+script:
+ - cabal configure --enable-tests --enable-benchmarks -v2
+ - cabal build
+ - cabal test
+ - cabal check
+ - cabal sdist
+
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
